### ISSUE TITLE
Not enough storage

### ISSUE THREAD

**Issue by FastAndreiiii** [izqalan/cy-client#66] opened 2021-10-15 01:08 UTC
what I want to download is only 1.80 gb
I have enough storage but it still gives me this error wherever I put the program
![Screenshot_1](https://user-images.githubusercontent.com/92557305/137416135-b27770dc-f011-4c60-afb1-f1f67786796e.png)

**Comment by FastAndreiiii** [comment] 2021-11-04 13:07
> Try changing the destination or redownloading the latest version.

apparently it goes with an older version

**Comment by Anequit** [comment] 2021-11-13 12:08
> > Try changing the destination or redownloading the latest version.
> 
> apparently it goes with an older version

Are you still having the issue?

**Comment by FastAndreiiii** [comment] 2021-11-14 14:45
> > > Try changing the destination or redownloading the latest version.
> > 
> > 
> > apparently it goes with an older version
> 
> Are you still having the issue?

Yes,but with old version no

**Comment by Anequit** [comment] 2021-11-14 15:15
That's really odd I'll take a look and see if I can spot any bugs

**Comment by FastAndreiiii** [comment] 2021-11-14 15:24
ok, it's very weird, i think it's because of new options you can see how much% is unloaded i think it has problems loading

**Comment by Anequit** [comment] 2021-11-14 15:45
I just released a fix for this issue. Let me know if the issue is still present.

**Comment by FastAndreiiii** [comment] 2021-11-14 16:04
stil i have it, i test with this link https://cyberdrop.me/a/dCdBg9n6 try it

**Comment by Anequit** [comment] 2021-11-14 16:09
![image](https://user-images.githubusercontent.com/51097472/141688859-25007077-5917-4ee3-93a1-fcdb02c52670.png)

working fine for me

**Comment by FastAndreiiii** [comment] 2021-11-14 16:16
wow strange.....

**Comment by Anequit** [comment] 2021-11-14 16:21
must be something to do with your system

**Comment by FastAndreiiii** [comment] 2021-11-16 20:55
> must be something to do with your system

hmmm win11 meaby?

**Comment by Anequit** [comment] 2021-11-17 13:53
> > must be something to do with your system
> 
> hmmm win11 meaby?

I'm running win11 and tested on w10 too it's working for me on both fine

**Comment by phaolo2** [comment] 2021-12-08 17:00
Happens to me too, with v2.2.2.0.
And the album I'm trying to download is only 400mb.
Btw, the destination folder is always forgotten at start..

**Comment by FastAndreiiii** [comment] 2021-12-08 17:45
> Happens to me too, with v2.2.2.0 x64. And the album I'm trying to download is only 400mb. Btw, the previous destination folder is always forgotten at start..

Yeeei i m not alone 🤣🤣🤣🤣🤣

**Comment by phaolo2** [comment] 2021-12-12 00:36
I used a different drive with the same computer and the download worked.
I guess there's some bug in detecting the free space that shows up only in certain conditions.

**Comment by Anequit** [comment] 2021-12-12 03:55
> I used a different drive with the same computer and the download worked. I guess there's some bug in detecting the free space that shows up only in certain conditions.

From what you said here I'm suspecting it's an issue with fragmentation on the drives. I regularly keep my drives in healthy condition, which is probably why I haven't had this issue, but someone who might have neglected it over time might be running into this issue.

**Comment by apollovictoria44** [comment] 2022-01-19 08:17
i'm here to report that i'm having the same issue.

**Comment by Anequit** [comment] 2022-01-23 01:50
https://github.com/izqalan/cy-client/releases/tag/v2.2.3

**Comment by FastAndreiiii** [comment] 2022-02-04 03:37
the bug is fix with last update <3

**Comment by Anequit** [comment] 2022-02-04 05:39
Glad to hear!

**Closed by Anequit** 2022-02-04 05:39 UTC
Labels: bug
